kpatch: retry kpatch load on failure
If a kpatch load fails due to an activeness safety check, try again, up
to 5 times.

Unfortunately, insmod doesn't return the error code reported by the
kernel.  So we have to parse its error output instead.

diff --git a/kpatch/kpatch b/kpatch/kpatch
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -165,7 +165,27 @@ load_module () {
 	fi
 
 	echo "loading patch module: $module"
-	insmod "$module"
+	local i=0
+	while true; do
+		out=$(insmod "$module" 2>&1)
+		[[ -z $out ]] && break
+		echo $out 1>&2
+		[[ ! $out =~ "Device or resource busy" ]] &&
+			die "failed to load module $module"
+
+		# "Device or resource busy" means the activeness safety check
+		# failed.  Retry in a few seconds.
+		i=$((i+1))
+		if [[ $i = 5 ]]; then
+			die "failed to load module $module"
+			break
+		else
+			warn "retrying..."
+			sleep 2
+		fi
+	done
+
+	return 0
 }
 
 unload_module () {
