kpatch: load core module in kpatch apply

diff --git a/kpatch/kpatch b/kpatch/kpatch
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -69,7 +69,25 @@ find_module () {
 	__find_module "${arg}"
 }
 
+find_core_module() {
+	COREMOD="/usr/local/lib/modules/$(uname -r)/kpatch/kpatch.ko"
+	[[ -f "$COREMOD" ]] && return
+
+	COREMOD="/usr/lib/modules/$(uname -r)/kpatch/kpatch.ko"
+	[[ -f "$COREMOD" ]] && return
+
+	return 1
+}
+
+core_module_loaded () {
+	grep -q "T kpatch_register" /proc/kallsyms
+}
+
 load_module () {
+	if ! core_module_loaded; then
+		find_core_module || die "can't find core module"
+		/usr/sbin/insmod "$COREMOD" || die "failed to load core module"
+	fi
 	/usr/sbin/insmod "$1"
 }
 
