kpatch-build: allow overriding of distro name
It is sometimes useful to have ability to override
distro name, for example during cross-compilation
build when livepatch modules will be ran on the
target which differs from host.

This patch adds a new --distro option which
implements all needed functionality

Signed-off-by: Ruslan Bilovol <rbilovol@cisco.com>

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -387,12 +387,13 @@ usage() {
 	echo "		                   (can be specified multiple times)" >&2
 	echo "		--cross-compile    Specify the prefix used for all executables" >&2
 	echo "		                   used during compilation" >&2
+	echo "		--distro           Override distro name" >&2
 	echo "		--skip-cleanup     Skip post-build cleanup" >&2
 	echo "		--skip-gcc-check   Skip gcc version matching check" >&2
 	echo "		                   (not recommended)" >&2
 }
 
-options="$(getopt -o ha:r:s:c:v:j:t:n:o:d -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,cross-compile:,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o ha:r:s:c:v:j:t:n:o:d -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,cross-compile:,distro:,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -452,6 +453,10 @@ while [[ $# -gt 0 ]]; do
 		;;
 	--cross-compile)
 		KPATCH_CROSS_COMPILE="$2"
+		shift
+		;;
+	--distro)
+		DISTRO="$2"
 		shift
 		;;
 	--skip-cleanup)
@@ -530,7 +535,7 @@ fi
 # Don't check external file.
 # shellcheck disable=SC1091
 source /etc/os-release
-DISTRO="$ID"
+DISTRO="${DISTRO:-${ID}}"
 if [[ "$DISTRO" = fedora ]] || [[ "$DISTRO" = rhel ]] || [[ "$DISTRO" = ol ]] || [[ "$DISTRO" = centos ]]; then
 	[[ -z "$VMLINUX" ]] && VMLINUX="/usr/lib/debug/lib/modules/$ARCHVERSION/vmlinux"
 	[[ -e "$VMLINUX" ]] || die "kernel-debuginfo-$ARCHVERSION not installed"
