kpatch: use relative paths for finding tools/data
Use relative paths so that kpatch and kpatch-build will find the tools
and data they need, regardless of the installation prefix.  Also add
support for running them straight from the git repo.

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -24,8 +24,7 @@
 
 BASE="$PWD"
 LOGFILE="$PWD/kpatch-build.log"
-TOOLSDIR=/usr/local/libexec/kpatch
-DATADIR=/usr/local/share/kpatch
+TOOLSDIR="$(readlink -f $(dirname $0))"
 ARCHVERSION="$(uname -r)"
 DISTROVERSION="${ARCHVERSION%*.*}"
 CPUS="$(grep -c ^processor /proc/cpuinfo)"
@@ -44,6 +43,18 @@ die() {
 	echo "ERROR: kpatch build failed" >&2
 	echo "check kpatch-build.log for more details" >&2
 	exit 1
+}
+
+find_data_dir() {
+	# git repo
+	DATADIR="$(readlink -f $TOOLSDIR/../kmod)"
+	[[ -e "$DATADIR" ]] && return
+
+	# installation path
+	DATADIR="$(readlink -f $TOOLSDIR/../../share/kpatch)"
+	[[ -e "$DATADIR" ]] && return
+
+	return 1
 }
 
 if [[ "$#" -ne 1 ]]; then
@@ -97,6 +108,8 @@ else
 	echo "Creating cache"
 	tar czf "$KSRCDIR_CACHE" -C "$KSRCDIR_DIR" "$ARCHVERSION" >> "$LOGFILE" 2>&1 || die
 fi
+
+find_data_dir || (echo "can't find data dir" >&2 && die)
 
 cp -R "$DATADIR/core" "$DATADIR/patch" "$TEMPDIR" || die
 cp vmlinux "$TEMPDIR" || die
diff --git a/kpatch/kpatch b/kpatch/kpatch
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -10,7 +10,6 @@ KERNELRELEASE="$(uname -r)"
 SYSDIR="/usr/lib/kpatch/$KERNELRELEASE"
 USERDIR="/var/lib/kpatch/$KERNELRELEASE"
 ENABLEDDIR="$USERDIR/enabled"
-TOOLSDIR=/usr/local/libexec/kpatch
 
 usage () {
 	echo "usage:" >&2
@@ -68,6 +67,20 @@ echo_patch_name() {
 	NAME="${NAME%.ko}"
 	NAME="${NAME#kpatch-}"
 	echo $NAME
+}
+
+find_kpatch_build() {
+	SCRIPTDIR="$(readlink -f $(dirname $0))"
+
+	# git repo
+	KPATCHBUILD="$(readlink -f $SCRIPTDIR/../kpatch-build/kpatch-build)"
+	[[ -e "$KPATCHBUILD" ]] && return
+
+	# installation path
+	KPATCHBUILD="$(readlink -f $SCRIPTDIR/../libexec/kpatch/kpatch-build)"
+	[[ -e "$KPATCHBUILD" ]] && return
+
+	return 1
 }
 
 unset MODULE
@@ -148,9 +161,9 @@ case "$1" in
 	;;
 
 "build")
-	[[ "$#" -ne 2 ]] && usage
+	find_kpatch_build || die "kpatch-build is not installed"
 	shift
-	"$TOOLSDIR/kpatch-build" "$@" || die "kpatch build failed"
+	"$KPATCHBUILD" "$@" || die "kpatch build failed"
 	;;
 
 *)
