kpatch-build: don't ask to reverse apply patch
If the patch had already been mistakenly applied to the source tree,
don't ask the user if it should be reverse applied.  Instead, just exit
with an error.

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -185,7 +185,7 @@ fi
 echo "Testing patch file"
 cd "$SRCDIR" || die
 cp "$PATCHFILE" "$APPLIEDPATCHFILE" || die
-patch -p1 < "$APPLIEDPATCHFILE" || die "source patch file failed to apply"
+patch -N -p1 < "$APPLIEDPATCHFILE" || die "source patch file failed to apply"
 patch -p1 -R < "$APPLIEDPATCHFILE" &> /dev/null || die "reverse patch apply failed"
 
 echo "Building original kernel"
@@ -195,7 +195,7 @@ cp -LR "$DATADIR/patch" "$TEMPDIR" || die
 cp "$OBJDIR/vmlinux" "$TEMPDIR" || die
 
 echo "Building patched kernel"
-patch -p1 < "$APPLIEDPATCHFILE" >> "$LOGFILE" 2>&1 || die
+patch -N -p1 < "$APPLIEDPATCHFILE" >> "$LOGFILE" 2>&1 || die
 make "-j$CPUS" vmlinux "O=$OBJDIR" 2>&1 | tee -a "$TEMPDIR/patched_build.log" >> "$LOGFILE"
 [[ "${PIPESTATUS[0]}" -eq 0 ]] || die
 
