kpatch-build: add cross-compilation support
This patch introduces new option for kpatch-build
script "--cross-compile" which can be used for
specifying cross-complier prefix.
It allows to build live patches not only on
target system, but also on hosts for a target other
than the one on which the compiler is running

Also removed quotes in exec lines, so it is
possible to pass multy-component strings like
"ccache x86_64-xelinux-linux-" as cross-compiler

Signed-off-by: Ruslan Bilovol <rbilovol@cisco.com>

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -198,7 +198,7 @@ gcc_version_check() {
 	# gcc --version varies between distributions therefore extract version
 	# by compiling a test file and compare it to vmlinux's version.
 	echo 'void main(void) {}' > "$c"
-	out="$(gcc -c -pg -ffunction-sections -o "$o" "$c" 2>&1)"
+	out="$(${KPATCH_CROSS_COMPILE}gcc -c -pg -ffunction-sections -o "$o" "$c" 2>&1)"
 	gccver="$(gcc_version_from_file "$o")"
 	kgccver="$(gcc_version_from_file "$VMLINUX")"
 	rm -f "$c" "$o"
@@ -385,12 +385,14 @@ usage() {
 	echo "		-d, --debug        Enable 'xtrace' and keep scratch files" >&2
 	echo "		                   in <CACHEDIR>/tmp" >&2
 	echo "		                   (can be specified multiple times)" >&2
+	echo "		--cross-compile    Specify the prefix used for all executables" >&2
+	echo "		                   used during compilation" >&2
 	echo "		--skip-cleanup     Skip post-build cleanup" >&2
 	echo "		--skip-gcc-check   Skip gcc version matching check" >&2
 	echo "		                   (not recommended)" >&2
 }
 
-options="$(getopt -o ha:r:s:c:v:j:t:n:o:d -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o ha:r:s:c:v:j:t:n:o:d -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,cross-compile:,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -447,6 +449,10 @@ while [[ $# -gt 0 ]]; do
 		if [[ $DEBUG -eq 1 ]]; then
 			echo "DEBUG mode enabled"
 		fi
+		;;
+	--cross-compile)
+		KPATCH_CROSS_COMPILE="$2"
+		shift
 		;;
 	--skip-cleanup)
 		echo "Skipping cleanup"
@@ -694,6 +700,8 @@ if [[ $DEBUG -ge 4 ]]; then
 	export KPATCH_GCC_DEBUG=1
 fi
 
+export KPATCH_CROSS_COMPILE
+
 echo "Building original kernel"
 ./scripts/setlocalversion --save-scmversion || die
 make mrproper 2>&1 | logger || die
@@ -848,6 +856,7 @@ cd "$TEMPDIR/patch" || die
 KPATCH_BUILD="$SRCDIR" KPATCH_NAME="$MODNAME" \
 KBUILD_EXTRA_SYMBOLS="$KBUILD_EXTRA_SYMBOLS" \
 KPATCH_LDFLAGS="$KPATCH_LDFLAGS" \
+CROSS_COMPILE="$KPATCH_CROSS_COMPILE" \
 	make 2>&1 | logger || die
 
 if ! "$KPATCH_MODULE"; then
