check that logfile exists before printing message
Don't tell the user to check a log file that doesn't exist

Signed-off-by: Seth Jennings <sjenning@redhat.com>

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -60,7 +60,8 @@ die() {
 		msg="$1"
 	fi
 
-	echo "ERROR: $msg. Check $LOGFILE for more details." >&2
+	echo "ERROR: $msg." >&2
+	[[ -e $LOGFILE ]] && echo "Check $LOGFILE for more details." >&2
 
 	exit 1
 }
