kpatch-build: Add -a, --archversion commandline option
This can be used for building a kpatch module for a non-running
kernel. Note that the correct kernel and debug packages still need
to be installed.

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -356,6 +356,7 @@ usage() {
 	echo "usage: $(basename "$0") [options] <patch1 ... patchN>" >&2
 	echo "		patchN             Input patchfile(s)" >&2
 	echo "		-h, --help         Show this help message" >&2
+	echo "		-a, --archversion  Specify the kernel arch version" >&2
 	echo "		-r, --sourcerpm    Specify kernel source RPM" >&2
 	echo "		-s, --sourcedir    Specify kernel source directory" >&2
 	echo "		-c, --config       Specify kernel config file" >&2
@@ -370,7 +371,7 @@ usage() {
 	echo "		                   (not recommended)" >&2
 }
 
-options="$(getopt -o hr:s:c:v:j:t:n:o:d -l "help,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o ha:r:s:c:v:j:t:n:o:d -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -379,6 +380,10 @@ while [[ $# -gt 0 ]]; do
 	-h|--help)
 		usage
 		exit 0
+		;;
+	-a|--archversion)
+		ARCHVERSION="$2"
+		shift
 		;;
 	-r|--sourcerpm)
 		[[ ! -f "$2" ]] && die "source rpm '$2' not found"
