kpatch-build: Add -a, --archversion commandline option
This can be used for building a kpatch module for a non-running
kernel. Note that the correct kernel and debug packages still need
to be installed.

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -37,7 +37,6 @@
 BASE="$PWD"
 SCRIPTDIR="$(readlink -f "$(dirname "$(type -p "$0")")")"
 ARCH="$(uname -m)"
-ARCHVERSION="$(uname -r)"
 CPUS="$(getconf _NPROCESSORS_ONLN)"
 CACHEDIR="${CACHEDIR:-$HOME/.kpatch}"
 SRCDIR="$CACHEDIR/src"
@@ -356,6 +355,7 @@ usage() {
 	echo "usage: $(basename "$0") [options] <patch1 ... patchN>" >&2
 	echo "		patchN             Input patchfile(s)" >&2
 	echo "		-h, --help         Show this help message" >&2
+	echo "		-a, --archversion  Specify the kernel arch version" >&2
 	echo "		-r, --sourcerpm    Specify kernel source RPM" >&2
 	echo "		-s, --sourcedir    Specify kernel source directory" >&2
 	echo "		-c, --config       Specify kernel config file" >&2
@@ -370,7 +370,7 @@ usage() {
 	echo "		                   (not recommended)" >&2
 }
 
-options="$(getopt -o hr:s:c:v:j:t:n:o:d -l "help,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o ha:r:s:c:v:j:t:n:o:d -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -380,13 +380,14 @@ while [[ $# -gt 0 ]]; do
 		usage
 		exit 0
 		;;
+	-a|--archversion)
+		ARCHVERSION="$2"
+		shift
+		;;
 	-r|--sourcerpm)
 		[[ ! -f "$2" ]] && die "source rpm '$2' not found"
 		SRCRPM="$(readlink -f "$2")"
 		shift
-		rpmname="$(basename "$SRCRPM")"
-		ARCHVERSION="${rpmname%.src.rpm}.$(uname -m)"
-		ARCHVERSION="${ARCHVERSION#kernel-}"
 		;;
 	-s|--sourcedir)
 		[[ ! -d "$2" ]] && die "source dir '$2' not found"
@@ -449,12 +450,31 @@ if [[ ${#PATCH_LIST[@]} -eq 0 ]]; then
 	exit 1
 fi
 
+if [[ -n "$ARCHVERSION" ]] && [[ -n "$VMLINUX" ]]; then
+	warn "--archversion is incompatible with --vmlinux"
+	exit 1
+fi
+
+if [[ -n "$SRCRPM" ]]; then
+	if  [[ -n "$ARCHVERSION" ]]; then
+		warn "--archversion is incompatible with --sourcerpm"
+		exit 1
+	fi
+	rpmname="$(basename "$SRCRPM")"
+	ARCHVERSION="${rpmname%.src.rpm}.$(uname -m)"
+	ARCHVERSION="${ARCHVERSION#kernel-}"
+fi
+
 # ensure cachedir and tempdir are setup properly and cleaned
 mkdir -p "$TEMPDIR" || die "Couldn't create $TEMPDIR"
 rm -rf "${TEMPDIR:?}"/*
 rm -f "$LOGFILE"
 
 if [[ -n "$USERSRCDIR" ]]; then
+	if [[ -n "$ARCHVERSION" ]]; then
+		warn "--archversion is incompatible with --sourcedir"
+		exit 1
+	fi
 	SRCDIR="$USERSRCDIR"
 
 	[[ -z "$VMLINUX" ]] && VMLINUX="$SRCDIR"/vmlinux
@@ -463,6 +483,8 @@ if [[ -n "$USERSRCDIR" ]]; then
 	# Extract the target kernel version from vmlinux in this case.
 	ARCHVERSION="$(strings "$VMLINUX" | grep -e "^Linux version" | awk '{ print($3); }')"
 fi
+
+[[ -z "$ARCHVERSION" ]] && ARCHVERSION="$(uname -r)"
 
 [[ "$SKIPCLEANUP" -eq 0 ]] && trap cleanup EXIT INT TERM HUP
 
