add build caching

diff --git a/scripts/kpatch-build b/scripts/kpatch-build
--- a/scripts/kpatch-build
+++ b/scripts/kpatch-build
@@ -30,6 +30,8 @@ DISTROVERSION=${ARCHVERSION%*.*}
 CPUS=$(grep -c ^processor /proc/cpuinfo)
 LOCALVERSION=$(uname -r)
 LOCALVERSION=-${LOCALVERSION##*-}
+KSRCDIR=~/.kpatch/$ARCHVERSION
+KSRCDIR_CACHE=$KSRCDIR.cache
 
 cleanup() {
 	rm -Rf kernel-$DISTROVERSION.src.rpm rpmbuild $LOGFILE $TEMPDIR > /dev/null 2>/dev/null
@@ -55,28 +57,40 @@ fi
 
 cleanup
 
-echo "Verifying required development tools"
-yum install rpmdevtools yum-utils || die
-
-echo "Downloading kernel source for $ARCHVERSION"
-yumdownloader --source kernel-$ARCHVERSION || die
-
-echo "Verifying build dependencies for kernel package"
-yum-builddep kernel-$DISTROVERSION.src.rpm || die
-
-echo "Unpacking kernel source"
-rpmdev-setuptree >> $LOGFILE 2>&1 || die
-rpm -Uvh kernel-$DISTROVERSION.src.rpm >> $LOGFILE 2>&1 || die
-cd ~/rpmbuild/SPECS || die
-rpmbuild -bp --target=$(uname -m) kernel.spec >> $LOGFILE 2>&1 || die
-cd ~/rpmbuild/BUILD/kernel-* || die
-cd linux-$ARCHVERSION || die
-BUILD=$PWD
-echo $LOCALVERSION > localversion
-
-echo "Building the base kernel"
-make -j$CPUS vmlinux >> $LOGFILE 2>&1 || die
 TEMPDIR=`mktemp -d` || die
+
+if [ -d "$KSRCDIR_CACHE" ]
+then
+	echo "Using kernel source compile cache at $KSRCDIR_CACHE"
+	rm -rf $KSRCDIR
+	cp -a $KSRCDIR_CACHE $KSRCDIR
+	cd $KSRCDIR
+else
+	echo "Verifying required development tools"
+	yum install rpmdevtools yum-utils || die
+
+	echo "Downloading kernel source for $ARCHVERSION"
+	yumdownloader --source kernel-$ARCHVERSION || die
+
+	echo "Verifying build dependencies for kernel package"
+	yum-builddep kernel-$DISTROVERSION.src.rpm || die
+
+	echo "Unpacking kernel source"
+	rpmdev-setuptree >> $LOGFILE 2>&1 || die
+	rpm -Uvh kernel-$DISTROVERSION.src.rpm >> $LOGFILE 2>&1 || die
+	rpmbuild -bp --target=$(uname -m) ~/rpmbuild/SPECS/kernel.spec >> $LOGFILE 2>&1 || die
+	rm -rf $KSRCDIR
+	mkdir -p ~/.kpatch
+	mv ~/rpmbuild/BUILD/kernel-*/linux-$ARCHVERSION $KSRCDIR >> $LOGFILE 2>&1 || die
+
+	echo "Building the base kernel"
+	cd $KSRCDIR
+	echo $LOCALVERSION > localversion
+	make -j$CPUS vmlinux >> $LOGFILE 2>&1 || die
+
+	cp -a $KSRCDIR $KSRCDIR_CACHE
+fi
+
 cp -R $KPATCHPATH/* $TEMPDIR || die
 cp vmlinux $TEMPDIR || die
 
@@ -124,7 +138,7 @@ done
 echo "Building hotfix module"
 ld -r -o output.o output/* >> $LOGFILE 2>&1 || die
 ./tools/add-patches-section output.o vmlinux >> $LOGFILE 2>&1 || die
-KPATCH_BUILD=$BUILD make >> $LOGFILE 2>&1 || die
+KPATCH_BUILD=$KSRCDIR make >> $LOGFILE 2>&1 || die
 strip -d kpatch-patch.ko >> $LOGFILE 2>&1 || die
 ./tools/link-vmlinux-syms kpatch-patch.ko vmlinux >> $LOGFILE 2>&1 || die
 
