test/integration: run -FAIL tests when invoked with --quick
Include -FAIL tests as well as combined in 'quick' target.

Signed-off-by: Artem Savkov <asavkov@redhat.com>

diff --git a/test/integration/kpatch-test b/test/integration/kpatch-test
--- a/test/integration/kpatch-test
+++ b/test/integration/kpatch-test
@@ -63,7 +63,7 @@ usage() {
 	echo "		-h, --help	Show this help message" >&2
 	echo "		-c, --cached	Don't rebuild patch modules" >&2
 	echo "		-d, --directory	Patch directory" >&2
-	echo "		-q, --quick	Just combine all patches into one module for testing" >&2
+	echo "		-q, --quick	Test combined patch and -FAIL patches only" >&2
 }
 
 options=$(getopt -o hcd:q -l "help,cached,directory,quick" -- "$@") || exit 1
@@ -294,11 +294,11 @@ run_combined_test() {
 echo "clearing printk buffer"
 sudo dmesg -C
 
-if [[ $QUICK != 1 ]]; then
-	for file in "${PATCH_LIST[@]}"; do
+for file in "${PATCH_LIST[@]}"; do
+	if [[ $QUICK != 1 || $file =~ -FAIL ]]; then
 		build_module $file
-	done
-fi
+	fi
+done
 
 build_combined_module
 
