test: integration test cleanup
- fix kpatch tool path in multiple.test
- remove "kpatch replace" tests (replace is deprecated)

diff --git a/test/integration/kpatch-test b/test/integration/kpatch-test
--- a/test/integration/kpatch-test
+++ b/test/integration/kpatch-test
@@ -149,23 +149,8 @@ run_load_test() {
 	fi
 
 
-	if ! $KPATCH replace $module >> $LOG 2>&1; then
-		error "$prefix: kpatch replace failed"
-		return
-	fi
-
-	if [[ -e $testprog ]] && ! ./$testprog >> $LOG 2>&1; then
-		error "$prefix: $testprog failed after kpatch replace"
-		return
-	fi
-
-	if ! $KPATCH unload $module >> $LOG 2>&1; then
-		error "$prefix: kpatch unload failed"
-		return
-	fi
-
 	if [[ -e $testprog ]] && ./$testprog >> $LOG 2>&1; then
-		error "$prefix: $testprog succeeded after kpatch unload"
+		error "$prefix: $testprog succeeded before kpatch load"
 		return
 	fi
 
@@ -176,6 +161,15 @@ run_load_test() {
 
 	if [[ -e $testprog ]] && ! ./$testprog >> $LOG 2>&1; then
 		error "$prefix: $testprog failed after kpatch load"
+	fi
+
+	if ! $KPATCH unload $module >> $LOG 2>&1; then
+		error "$prefix: kpatch unload failed"
+		return
+	fi
+
+	if [[ -e $testprog ]] && ./$testprog >> $LOG 2>&1; then
+		error "$prefix: $testprog succeeded after kpatch unload"
 		return
 	fi
 }
@@ -241,17 +235,41 @@ run_combined_test() {
 
 	log "load test: combined module"
 
-	if ! $KPATCH replace kpatch-COMBINED.ko >> $LOG 2>&1; then
-		error "combined: kpatch replace failed"
+	unload_all
+
+	for testprog in *.test; do
+		[[ $testprog != *-LOADED.test ]] && continue
+		if ./$testprog >> $LOG 2>&1; then
+			error "combined: $testprog succeeded before kpatch load"
+			return
+		fi
+	done
+
+	if ! $KPATCH load kpatch-COMBINED.ko >> $LOG 2>&1; then
+		error "combined: kpatch load failed"
 		return
 	fi
 
 	for testprog in *.test; do
 		[[ $testprog != *-LOADED.test ]] && continue
 		if ! ./$testprog >> $LOG 2>&1; then
-			error "combined: $testprog failed"
+			error "combined: $testprog failed after kpatch load"
 		fi
 	done
+
+	if ! $KPATCH unload kpatch-COMBINED.ko >> $LOG 2>&1; then
+		error "combined: kpatch unload failed"
+		return
+	fi
+
+	for testprog in *.test; do
+		[[ $testprog != *-LOADED.test ]] && continue
+		if ./$testprog >> $LOG 2>&1; then
+			error "combined: $testprog succeeded after kpatch unload"
+			return
+		fi
+	done
+
 }
 
 echo "clearing printk buffer"
